#deploy frontend to firebase when pushing to main
name: Deploy to production
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && CI=false npm run build
      - run: echo "FIREBASE_SDK_CONFIG='${{ secrets.FIREBASE_SDK_CONFIG }}'" >> .env.production
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GEMMA_GARAGE}}'
          channelId: live
          projectId: gemma-garage
